import React from 'react';
import './styles/Legal.css';
import { usePageTitle } from './hooks/usePageTitle';

const PrivacyPolicy: React.FC = () => {
  usePageTitle('Privacy Policy - BrainTest');

  return (
    <div className="legal-page">
      {/* Hero Section */}
      <section className="legal-hero">
        <div className="legal-hero-content">
          <h1>Privacy Policy</h1>
        </div>
      </section>

      {/* Content Section */}
      <section className="legal-content">
        <div className="legal-container">
          <div style={{ marginBottom: '20px' }}>
            <p style={{ float: 'left', margin: 0 }}>Covered Entity Name: BrainTest Inc. SEZC</p>
            <p style={{ float: 'right', margin: 0 }}>Effective Date: October 5, 2023</p>
            <div style={{ clear: 'both' }}></div>
          </div>

          <p style={{ fontWeight: 'bold', fontSize: '1.1rem' }}>
            THIS PRIVACY POLICY DESCRIBES HOW HEALTH INFORMATION AND PRIVATE PERSONAL INFORMATION ABOUT YOU MAY BE USED AND DISCLOSED AND HOW YOU CAN GET ACCESS TO THIS INFORMATION
          </p>
          <p style={{ fontWeight: 'bold' }}>PLEASE REVIEW CAREFULLY</p>

          <p>
            The mobile application BrainTest and the website located at www.braintest.com (collectively "BrainTest") is provided by BrainTest Inc. SEZC. In this Privacy Policy ", "we" "us" or "our" refers to every entity that is providing BrainTest to you,
          </p>
          <p>
            We recognize the importance of privacy and the sensitivity of your personal Health Information (as defined below) and Private Personal Information (as defined below) and, as such, have created this Privacy Policy. We welcome your comments and/or suggestions on improving this Privacy Policy. If you have any concerns, please contact us at the address given below.
          </p>
          <p>
            The detailed Privacy Policy is given to all customers that use our products. If you have any questions about this Privacy Policy, please contact our Privacy Officer.
          </p>

          <h2>OUR PLEDGE REGARDING HEALTH INFORMATION:</h2>
          <p>The following are some, but not all types of the health information we may obtain from or about you ("Health Information):</p>
          <ul>
            <li>your health and medical history;</li>
            <li>your BrainTest test score results;</li>
            <li>metadata gathered by us from your interaction and use of BrainTest, for example the length of time it takes you to complete each question, and to complete the test as a whole;</li>
            <li>other health information you may provide us.</li>
          </ul>

          <p>
            We understand that Health Information about you is personal. We are committed to protecting your Health Information. We create a record of the services we provide. We need this record to provide you with quality services and to comply with certain legal requirements. This Privacy Policy applies to all of the records of your services generated by us. This Privacy Policy explains how we may use and disclose Health Information about you. We also describe your rights to this Health Information, and describe certain obligations we have regarding the use and disclosure of your Health Information. We are required by law to:
          </p>
          <ul>
            <li>make sure that Health Information that personally identifies you is kept private; and</li>
            <li>give you this notice of our legal duties &amp; privacy practices with respect to Health Information about you.</li>
          </ul>

          <p>
            We are also required to comply with any federal or state laws that impose stricter standards than the uses and disclosures described in this Privacy Policy.
          </p>

          <h2>HOW WE MAY USE AND DISCLOSE HEALTH INFORMATION ABOUT YOU.</h2>
          <p>
            The following categories describe different ways that we use and disclose your Health information. For each category of uses or disclosures we will explain what we mean and try to give some examples. Not every use or disclosure in a category will be listed. However, all of the ways we are permitted to use and disclose information will fall within one of the categories.
          </p>

          <h3>For Our Operations</h3>
          <p>
            We may use and disclose Health Information about you for operations of our business. These uses and disclosures are necessary to run our business and make sure that all of our customers receive quality services. For example, we may use Health Information to review our services and to evaluate the performance of our staff in providing you the services. We may also combine Health Information about many customers to decide what additional services we should offer, what services are not needed, or to compare how we are doing with others and to see where we can make improvements. We may remove information that specifically and/or uniquely identifies you from this set of Health Information so others may use it to study health care delivery without learning who our specific customers are.
          </p>

          <h3>Research</h3>
          <p>
            We may use and disclose your non-personally identifiable Health Information for research purposes. In no way will any personally identifiable information be included with any the Health Information that may be disclosed. All research projects, however, are subject to a special approval process by us and shall be at our sole discretion. This process evaluates a proposed research project and its use of Health Information, trying to balance the research needs with patients' need for privacy of their Health information. Before we use or disclose non-personally identifiable Health Information for research, the project will have been approved through this research approval process. We will always seek your pre-approval and ask for your specific permission if the researcher will have access to your name, address, or other personally identifiable information that reveals who you are, and you will always have the right to refuse to participate in such medical research or share such personally identifiable information with the researcher.
          </p>

          <h3>As Required By Law</h3>
          <p>
            We will disclose Health Information about you when required to do so by federal, state, or local law and in response to a court order, subpoena, warrant, summons or similar process. Prior to disclosing your Health Information in this manner, and only where we are permitted by law, we will attempt to advise you about such disclosure requests, but we can make no guarantees and will have no liability if we do not advise you prior to such disclosures.
          </p>

          <h3>Health Oversight Activities</h3>
          <p>
            We may disclose Health Information to a health oversight agency for activities authorized by law. These oversight activities include, for example, audits, investigations, inspections, and licensure. These activities are necessary for the government to monitor the health care system, government programs, and compliance with civil rights laws. Prior to disclosing your Health Information in this manner, and only where we are permitted by law, we will attempt to advise you about such disclosure requests, but we can make no guarantees and will have no liability if we do not advise you prior to such disclosures.
          </p>

          <h2>YOUR RIGHTS REGARDING HEALTH INFORMATION ABOUT YOU.</h2>
          <p>You have the following rights regarding Health Information we maintain about you:</p>

          <h3>Right to Inspect and Copy</h3>
          <p>
            You have the right to inspect your Health Information while under our supervision. You may also request copies of your Health Information that may be used to make decisions about your care. Usually, this includes health and billing records. To inspect and copy your health information, submit your request in writing to BrainTest Inc. SEZC. We may charge a fee for the costs of copying, mailing or other supplies and services associated with your request.
          </p>
          <p>
            We may deny your request to inspect and copy in certain very limited circumstances. If you are denied access to Health Information, you may request that the denial be reviewed. Another licensed health care professional chosen by our company will review your request and the denial. The person conducting the review will not be the person who denied your request. We will comply with the outcome of the review.
          </p>

          <h3>Right to Amend</h3>
          <p>
            If you feel that Health Information we have about you is incorrect or incomplete, you may ask us to amend the information. You have the right to request an amendment for as long as we keep the information. To request an amendment, your request must be made in writing, submitted to our Privacy Officer, and must be contained on one page of paper legibly handwritten or typed. In addition, you must provide a reason that supports your request for an amendment. We may deny your request for an amendment if it is not in writing or does not include a reason to support the request. In addition, we may deny your request if you ask us to amend information that:
          </p>
          <ul>
            <li>was not created by us, unless the person or entity that created the information is no longer available to make the amendment;</li>
            <li>is not part of the Health Information kept by or for our business;</li>
            <li>is not part of the information which you would be permitted to inspect and copy;</li>
            <li>or, is accurate and complete.</li>
          </ul>
          <p>
            Any amendment we make to your Health Information will be disclosed to those with whom we disclose information as previously specified.
          </p>

          <h3>Right to an Accounting of Disclosures</h3>
          <p>
            You may request an accounting for any disclosures of your Health Information we have made, except for uses and disclosures for services, payment, and health care operations, as previously described. To request this list of disclosures, you must submit your request in writing to our Privacy Officer. Your request must state a time period which may not be longer than six years and may not include dates before July 1, 2017. The first list you request within a 12-month period will be free. For additional lists, we may charge you for the costs of providing the list. We will notify you of the cost involved and you may choose to withdraw your request at that time before any costs are incurred. We will mail you a list of our disclosure records as they relate to your Health Information within 30 days of your request, or notify you if we are unable to supply the list within that time period and by what date we can supply the list; but this date will not be exceed a total of 60 days from the date you made the request.
          </p>

          <h2>OTHER USES OF HEALTH INFORMATION.</h2>
          <p>
            Other uses and disclosures of Health Information not covered by this Privacy Policy or the laws that apply to us will be made only with your written permission (which may be obtained digitally through your explicit implied consent). If you provide us permission to use or disclose Health Information about you, you may revoke that permission, in writing, at any time. If you revoke your permission, we will no longer use or disclose Health Information about you for the reasons covered by your written authorization. You understand that we are unable to take back any disclosures we have already made with your permission, and that we are required to retain our records of the services that we provided to you.
          </p>

          <h2>WHAT OTHER PERSONAL INFORMATION DO WE COLLECT?</h2>
          <p>
            We may collect the additional following types of information from or about you and your computer, mobile phone device and/or tablet (if applicable), which may include some information that can be used to identify you ("Private Personal Information"):
          </p>

          <h3>a) Information You Provide:</h3>
          <p>You may provide us with certain Private Personal Information, such as your:</p>
          <ul>
            <li>contact information such as name, phone number, email address, mailing address and mobile phone number;</li>
            <li>demographic information including age, gender and ethnicity;</li>
            <li>location;</li>
            <li>device and mobile device information such as device type, mobile device ID (including unique device identifier), browser type, and Internet service provider ("ISP");</li>
            <li>financial and billing information such as credit/debit card numbers, billing address and bank account number;</li>
            <li>preferences information you provide such as product or content interests, or communication or marketing preferences;</li>
            <li>usage activity about how you interact with us such as purchase history, what content you viewed, and which areas of BrainTest you visited; and</li>
            <li>any IP address uniquely associated with your computer or mobile device or tablet.</li>
            <li>or any other such information which you may provide us.</li>
          </ul>

          <h3>b) Cookies:</h3>
          <p>
            We, or a third party we engage to provide services to us, may store one or more cookies (a small text file containing a string of alphanumeric characters) on your device that uniquely identifies your browser. These cookies may store an API key, but no other personal information. BrainTest uses persistent cookies. A persistent cookie remains after you close your browser or mobile application, and may be used by your browser and mobile application on subsequent sessions of BrainTest. Persistent cookies can be removed by following your web browser help file directions. You can reset your web browser to refuse all cookies or to indicate when a cookie is being sent. However, BrainTest may not function properly if the ability to accept cookies is disabled. By using BrainTest, you agree to accept the placement of cookies on your mobile device browser.
          </p>

          <h3>c) Site Logs:</h3>
          <p>
            When you use BrainTest our servers may log certain information that your web browser sends to us. These logs may include information such as your web request, Internet Protocol address, type of device, type of browser, browser language, referring / exit pages and URLs, platform type, number of clicks, domain names, landing pages, pages viewed and the order of those pages, the amount of time spent on particular pages, the date and time of your request.
          </p>

          <h3>d) Analytics:</h3>
          <p>
            We may partner with third party agents to provide analytics on usage of BrainTest by our users. The data collected by our agents may include: agent version, platform, SDK version, timestamp, API key (identifier for application), application version, device identifier, iOS Identifier for Advertising, iOS Identifier for Vendors, Android Advertiser ID, Media Access Control (MAC) address, International Mobile Equipment Identity (IMEI), Model, manufacturer and OS version of device, session start/stop time, device uptime, locale (specific location where a given language is spoken), mobile network code/mobile country code, time zone, network status (Wi-Fi, etc.), memory, disk, CPU and battery usage information.
          </p>

          <h3>Traffic and Usage</h3>
          <p>
            We may monitor traffic patterns, usage and related information. We use this information in order to optimize and assess usage of BrainTest. We reserve the right to disclose information about your usage of BrainTest, and demographics in forms that do not reveal your personal identity.
          </p>

          <h3>Use of Personal Information</h3>
          <p>We may use your Private Personal Information that we collect for the following purposes:</p>
          <ul>
            <li>to administer BrainTest, including but not limited to building your BrainTest account and delivering you content from BrainTest, and scoring your BrainTest tests;</li>
            <li>to communicate with you for the purpose of informing you of changes or additions to BrainTest;</li>
            <li>to send you push notifications, text messages, or emails when you are using BrainTest. If you do not want these notifications, text messages or emails, you can manage your preferences either through your device's Notifications settings and/or in the BrainTest settings;</li>
            <li>to notify you about new products and services offered by us or our affiliates, subsidiaries and related companies and our trusted business partners that we believe may be of interest to you;</li>
            <li>to process your payments – after you place an order on BrainTest you will need to make payment for tests or subscriptions you have ordered. Your payment will be processed by us.</li>
            <li>to enforce this Privacy Policy;</li>
            <li>to send you marketing communications, including emails and text messages;</li>
            <li>to assess your needs to determine other suitable products or services;</li>
            <li>to respond to claims that any content in BrainTest violates the rights of third parties;</li>
            <li>to respond to your request for customer service;</li>
            <li>to protect our rights, property or personal safety and of our users and the public; or</li>
            <li>as required or authorized by law including, but not limited to in response to a subpoena, discovery request, or other lawful process.</li>
          </ul>
          <p>
            We do not and will not sell, rent, share or disclose your Health Information or Private Personal Information without first receiving your permission or as disclosed in this Privacy Policy.
          </p>

          <h3>Your Choices and Rights Regarding Your Private Personal Information</h3>
          <p>
            You may decline to submit Private Personal Information through BrainTest, in which case we may not be able to provide certain services to you. If you do not agree with our Privacy Policy or Terms of Use, please uninstall and discontinue your use of BrainTest; your continued usage of BrainTest will signify your consent to, and acceptance of our Privacy Policy and Terms of Use.
          </p>
          <p>
            We will take appropriate measures to ensure that the Private Personal Information we have about you is accurate, up to date, complete, relevant and not misleading. You have the right to access the Private Personal Information we have collected about you and, if such Private Personal Information is inaccurate, you have the right to request that we correct such Private Personal Information or erase it. Note that we have the right to deny your access to your Private Personal Information and we also have the right to refuse to correct such Private Personal Information but, if we deny you access or refuse to correct, we will provide a reason why. You also have the right to request that we attach to your Private Personal Information any statement you furnish to us that indicates how your Private Personal Information should be changed. Once a correction has been made or a statement of correction attached to your Private Personal Information, we will undertake to inform each person to whom such Private Personal Information has been disclosed of such correction or statement. We require at least 30 business days to correct your Private Personal Information, although we will acknowledge your request to correct your Private Personal Information within 20 business days of receiving your request.
          </p>
          <p>
            If you wish to access the Private Personal Information we have collected about you, contact our Privacy Officer at the address listed at the end of this Privacy Policy. We may request a reasonable fee to furnish you with the response you request.
          </p>
          <p>
            If we provide your Private Personal Information to third parties other than those who assist us in providing the BrainTest, we will notify you of the purpose for which the Private Personal Information is being shared. Your consent to such activity is implied because of our business relationship with you, but you may revoke your consent in the manner described above.
          </p>

          <h3>Transfer of Health Information and Private Personal Information</h3>
          <p>
            Your Health Information and Private Personal Information may be processed by us in the country in which it was collected and in other countries, including the United States and/or Canada, where laws regarding processing of Private Personal Information may be different than the laws in your country. Our servers may be located in the United States and Canada or other countries, and as such, your Health Information and Private Personal Information may be available to the U.S. government or its agencies under lawful orders made in the U.S.. Please be advised that through your continued use of BrainTest we may be transferring your Health Information and Private Personal Information to the U.S. and you expressly consent to that transfer and consent to be governed by U.S. law for these purposes.
          </p>
          <p>
            We may delete your Health Information and Private Personal Information when such information ceases to be necessary.
          </p>

          <h3>Summarized Data</h3>
          <p>
            We may also use your Private Personal Information to generate Summarized Data for internal use and for sharing with affiliates, subsidiaries, related companies and trusted business partners for planning and marketing purposes. "Summarized Data" means records which have been stripped of information potentially identifying individuals, and which have been manipulated or combined to provide generalized, anonymous information. Your identity, Health Information, and Private Personal Information will be kept anonymous in Summarized Data.
          </p>

          <h3>Consent</h3>
          <p>
            By providing Health Information and Private Personal Information to us and using BrainTest you voluntarily consent to the collection, use and disclosure of Health Information and Private Personal Information as specified in this Privacy Policy. Without limiting the foregoing, we may on occasion ask you to consent when we collect, use, or disclose your Health Information and Private Personal Information in specific circumstances. Sometimes we may imply your consent through your conduct with us, and rely on that, if the purpose of the collection, use or disclosure is obvious and you voluntarily provide the information.
          </p>
          <p>
            You may revoke any and/or all consents you have given to us; in order to revoke such consent(s), please contact our Privacy Officer in writing at the address listed at the end of these terms. At least 30 business days are required to effectuate your revocation of consent from the time we receive it. Please note, however, that revocation of any consent does not have retroactive effect.
          </p>

          <h3>Opting Out</h3>
          <p>
            You may wish to opt out of receiving certain information and communications from us. You may do so by contacting us at the addresses at the end of this Privacy Policy. If you wish to opt out of having cookies placed on your device you can do this be adjusting your browser settings as explained above.
          </p>

          <h3>Your Security and Health Information and Private Personal Information</h3>
          <p>
            We take reasonable steps to ensure that your Health Information and Private Personal Information is kept safe from loss, unauthorized access, modification or disclosure. However, due to the nature of wireless technology and potential security breaches, we cannot ensure the security or privacy of information you submit through BrainTest, including Health Information and Private Personal Information. Please remember that you control what Health Information and Private Personal Information you provide while using BrainTest. Ultimately, you are responsible for maintaining the secrecy of your Health Information and Private Personal Information in your possession. Always be careful and responsible regarding your Health Information and Private Personal Information. We are not responsible for, and cannot control, the use by others of any information which you provide to them or make public in any way and you should use caution in selecting the Health Information and Private Personal Information you provide to others.
          </p>

          <h3>Merger or Sale</h3>
          <p>
            In the event that we are acquired by or merged with a third party entity, we reserve the right to transfer or assign all your Health Information and Private Personal Information, and any other information we have collected from you and our users as part of such merger, acquisition, sale, or other change of control.
          </p>

          <h3>Right to a Paper Copy of This Privacy Policy</h3>
          <p>
            You have the right to obtain a paper copy of this Privacy Policy at any time. To obtain a copy, please request it by email to <a href="mailto:support@braintest.com">support@braintest.com</a>. You may also use the Internet to obtain a copy of this Privacy Policy from the "Contact Us" link at our website, <a href="http://www.braintest.com" target="_blank" rel="noopener noreferrer">www.braintest.com</a>. Even if you have received a notice electronically, you still retain the right to receive a paper copy upon request.
          </p>

          <h2>CHANGES TO THIS PRIVACY POLICY</h2>
          <p>
            We reserve the right to change this Privacy Policy. We reserve the right to make the revised or changed Privacy Policy effective for Health Information and Private Personal Information we already have about you as well as any information we receive in the future. We will post a copy of the current Privacy Policy in BrainTest. The Privacy Policy will contain on the first page, in the top right-hand corner, the effective date.
          </p>

          <h2>COMPLAINTS</h2>
          <p>
            If you believe your privacy rights have been violated, you may file a complaint with us. To file a complaint with us, contact the Practice Privacy Officer. All complaints must be submitted in writing.
          </p>
          <p>
            <strong>BrainTest Inc. SEZC, Privacy Officer</strong><br />
            PO Box CEC – 87, George Town, Grand Cayman, Cayman Islands, KY1-9012
          </p>

          <p className="legal-footer">
            <strong>Effective Date</strong><br />
            October 5, 2023 BrainTest Inc. SEZC | all rights reserved
          </p>
        </div>
      </section>
    </div>
  );
};

export default PrivacyPolicy;